// Web view HTML generation for long output

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { insertArtifact } = require("./db");

const VIEWS_DIR = process.env.VIEWS_DIR || "/data/views";
const ARTIFACT_TTL_MS = 30 * 60 * 1000; // 30 minutes

/**
 * Generate an HTML web view for long output.
 * @param {string} type - "diff" | "code" | "build" | "general"
 * @param {string} content - The full output content
 * @param {{ title?: string, diffs?: string, diffSummary?: string }} metadata
 * @returns {{ id: string, filePath: string }}
 */
function generateView(type, content, metadata = {}) {
  const id = crypto.randomUUID();
  const filePath = path.join(VIEWS_DIR, `${id}.html`);

  const html = renderTemplate(type, content, { ...metadata, id });
  fs.writeFileSync(filePath, html, "utf-8");

  insertArtifact({ id, type, filePath, ttlMs: ARTIFACT_TTL_MS });

  console.log(`[VIEW] Generated ${type} view: ${id}`);
  return { id, filePath };
}

function renderTemplate(type, content, metadata) {
  let body;

  switch (type) {
    case "diff":
      body = renderDiff(content, metadata);
      break;
    case "code":
      body = renderCode(content);
      break;
    case "build":
      body = renderLog(content);
      break;
    case "general":
    default:
      body = renderGeneral(content);
      break;
  }

  return baseLayout(metadata.title || `Output — ${type}`, body);
}

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderDiff(content, metadata) {
  const diffContent = metadata.diffs || content;
  const summary = metadata.diffSummary || "";

  return `
    ${summary ? `<div class="summary">${escapeHtml(summary)}</div>` : ""}
    <pre><code class="language-diff">${escapeHtml(diffContent)}</code></pre>
  `;
}

function renderCode(content) {
  return `<pre><code>${escapeHtml(content)}</code></pre>`;
}

function renderLog(content) {
  // Highlight pass/fail lines
  const lines = content.split("\n").map((line) => {
    if (/PASS|✓|passed/i.test(line)) {
      return `<span class="pass">${escapeHtml(line)}</span>`;
    }
    if (/FAIL|✗|failed|ERROR/i.test(line)) {
      return `<span class="fail">${escapeHtml(line)}</span>`;
    }
    return escapeHtml(line);
  });

  return `<pre class="log">${lines.join("\n")}</pre>`;
}

function renderGeneral(content) {
  return `<pre>${escapeHtml(content)}</pre>`;
}

function baseLayout(title, body) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css">
  <style>
    :root {
      --bg: #0d1117;
      --fg: #c9d1d9;
      --border: #30363d;
      --accent: #58a6ff;
      --pass: #3fb950;
      --fail: #f85149;
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #ffffff;
        --fg: #1f2328;
        --border: #d0d7de;
        --accent: #0969da;
        --pass: #1a7f37;
        --fail: #cf222e;
      }
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--fg);
      padding: 16px;
      line-height: 1.5;
      font-size: 16px;
    }
    h1 {
      font-size: 1.25rem;
      margin-bottom: 12px;
      border-bottom: 1px solid var(--border);
      padding-bottom: 8px;
    }
    .summary {
      background: var(--border);
      padding: 12px;
      border-radius: 8px;
      margin-bottom: 12px;
      font-family: monospace;
      font-size: 14px;
    }
    pre {
      background: var(--border);
      padding: 12px;
      border-radius: 8px;
      overflow-x: auto;
      font-size: 13px;
      line-height: 1.45;
      -webkit-overflow-scrolling: touch;
    }
    code { font-family: "SF Mono", SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace; }
    .pass { color: var(--pass); }
    .fail { color: var(--fail); font-weight: bold; }
    .log { white-space: pre-wrap; word-break: break-all; }
    .meta {
      margin-top: 16px;
      font-size: 12px;
      color: #8b949e;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  ${body}
  <div class="meta">Generated by TextSlash &middot; Expires in 30 minutes</div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
  <script>hljs.highlightAll();</script>
</body>
</html>`;
}

/**
 * Render the "expired" page for 410 Gone responses.
 */
function renderExpiredPage() {
  return baseLayout("View Expired", `
    <div style="text-align:center; padding: 40px 16px;">
      <p style="font-size: 1.5rem; margin-bottom: 12px;">This view has expired</p>
      <p>Output views are available for 30 minutes after generation.</p>
      <p style="margin-top: 16px;">Run the command again to see fresh output.</p>
    </div>
  `);
}

module.exports = { generateView, renderExpiredPage, VIEWS_DIR };
